FROM apache/airflow:2.5.1-python3.9

USER root
# Install system packages required for compiling psycopg2 and other packages
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         build-essential \
         libpq-dev \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow

# Copy requirements file and install
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir --user -r /requirements.txt
