# Part of: E-commerce ETL Pipeline & RAG Support Assistant
"""
Main entry point for the FastAPI application.
Exposes endpoints for checking health, querying the RAG support assistant,
and retrieving business metrics from PostgreSQL.
"""

import os
from pathlib import Path
import pandas as pd
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy import create_engine

# Load environment variables on startup
load_dotenv()

# Import the RAG chain helper
from rag.chain import get_qa_chain

app = FastAPI(
    title="E-commerce ETL & RAG Support Assistant API",
    description="REST API for querying the business database metrics and RAG support assistant.",
    version="1.0.0"
)

# Enable CORS for frontend deployment (e.g., on Vercel)
from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Permits all origins; in production, you can restrict this to your specific Vercel URL
    allow_credentials=True,
    allow_methods=["*"],  # Allows all HTTP methods (GET, POST, etc.)
    allow_headers=["*"],  # Allows all headers
)

# Initialize engine for metrics endpoints
db_url = os.getenv("DB_URL")
if not db_url:
    print("Warning: DB_URL is not set in environment.")
    engine = None
else:
    engine = create_engine(db_url)

# Initialize qa_chain at the module level once (not per request)
qa_chain = None
try:
    # Attempt to initialize the chain if the vector store exists
    qa_chain = get_qa_chain()
except Exception as e:
    print(f"Warning: Could not initialize RAG QA chain on startup. Details: {e}")
    print("Please make sure you run 'python rag/embed.py' to generate the Chroma vector store.")

# --- Pydantic Models ---

class QueryRequest(BaseModel):
    question: str = Field(..., description="The natural language question to ask the support assistant.")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the assistant.")
    sources: list[str] = Field(..., description="Snippets from the documents used as source context.")
    source_count: int = Field(..., description="The number of source documents retrieved.")

class RevenueRow(BaseModel):
    month: str
    total_revenue: float
    order_count: int

class ProductRow(BaseModel):
    description: str
    total_quantity: int
    total_revenue: float

class CustomerRow(BaseModel):
    CustomerID: int
    total_revenue: float
    order_count: int

# --- API Endpoints ---

@app.get("/health")
def health_check():
    """
    Simple health check endpoint returning service status and version.
    """
    try:
        print("[API] Health check invoked.")
        return {"status": "ok", "version": "1.0.0"}
    except Exception as e:
        print(f"[API] Health check failed: {e}")
        raise HTTPException(status_code=500, detail=f"Health check failed: {e}")

@app.post("/ask", response_model=QueryResponse)
def ask_question(request: QueryRequest):
    """
    Accepts a natural language question, queries ChromaDB and ChatOpenAI,
    and returns the answer along with sources and count.
    """
    global qa_chain
    print(f"[API] Received question: '{request.question}'")
    
    # 1. Validate question is not empty
    if not request.question or not request.question.strip():
        print("[API] 400 Error: Question is empty.")
        raise HTTPException(status_code=400, detail="Question is empty. Please provide a valid query.")
        
    # 2. Try to lazy-load the QA chain if it wasn't initialized on startup
    if qa_chain is None:
        try:
            print("[API] Attempting to lazy-load QA chain...")
            qa_chain = get_qa_chain()
        except Exception as e:
            print(f"[API] Failed to initialize QA chain: {e}")
            raise HTTPException(
                status_code=500,
                detail=f"QA chain is not ready. Make sure Chroma store is populated by running the embedding script. Error: {e}"
            )
            
    # 3. Call the QA chain
    try:
        print("[API] Querying QA chain...")
        result = qa_chain({"query": request.question})
        
        answer = result["result"]
        source_docs = result.get("source_documents", [])
        
        # Format sources: take first 150 characters of each document
        sources = []
        for doc in source_docs:
            snippet = doc.page_content[:150]
            sources.append(snippet)
            
        print(f"[API] Completed query successfully. Found {len(sources)} sources.")
        return QueryResponse(
            answer=answer,
            sources=sources,
            source_count=len(sources)
        )
    except Exception as e:
        print(f"[API] Error running QA chain: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to query QA assistant: {e}")

@app.get("/metrics/revenue", response_model=list[RevenueRow])
def get_monthly_revenue():
    """
    Queries monthly_revenue table from PostgreSQL and returns list ordered by month ascending.
    """
    print("[API] Fetching monthly revenue metrics...")
    if not engine:
        raise HTTPException(status_code=500, detail="Database engine is not initialized.")
        
    try:
        with engine.connect() as conn:
            df = pd.read_sql("SELECT month, total_revenue, order_count FROM monthly_revenue ORDER BY month ASC", conn)
            
        records = df.to_dict(orient="records")
        print(f"[API] Retrieved {len(records)} monthly revenue records.")
        return [RevenueRow(**r) for r in records]
    except Exception as e:
        print(f"[API] Error fetching monthly revenue: {e}")
        raise HTTPException(status_code=500, detail=f"Database error: {e}")

@app.get("/metrics/top-products", response_model=list[ProductRow])
def get_top_products():
    """
    Queries top_products table from PostgreSQL and returns top 20 by total_revenue.
    """
    print("[API] Fetching top products metrics...")
    if not engine:
        raise HTTPException(status_code=500, detail="Database engine is not initialized.")
        
    try:
        with engine.connect() as conn:
            # Query top 20 by total_revenue
            df = pd.read_sql("SELECT description, total_quantity, total_revenue FROM top_products ORDER BY total_revenue DESC LIMIT 20", conn)
            
        records = df.to_dict(orient="records")
        print(f"[API] Retrieved {len(records)} top product records.")
        return [ProductRow(**r) for r in records]
    except Exception as e:
        print(f"[API] Error fetching top products: {e}")
        raise HTTPException(status_code=500, detail=f"Database error: {e}")

@app.get("/metrics/top-customers", response_model=list[CustomerRow])
def get_top_customers():
    """
    Queries top_customers table from PostgreSQL and returns top 20 by total_revenue.
    """
    print("[API] Fetching top customers metrics...")
    if not engine:
        raise HTTPException(status_code=500, detail="Database engine is not initialized.")
        
    try:
        with engine.connect() as conn:
            # Query top 20 by total_revenue
            df = pd.read_sql('SELECT "CustomerID", total_revenue, order_count FROM top_customers ORDER BY total_revenue DESC LIMIT 20', conn)
            
        # Standardize CustomerID as integer
        df["CustomerID"] = df["CustomerID"].astype(float).astype(int)
        records = df.to_dict(orient="records")
        print(f"[API] Retrieved {len(records)} top customer records.")
        return [CustomerRow(**r) for r in records]
    except Exception as e:
        print(f"[API] Error fetching top customers: {e}")
        raise HTTPException(status_code=500, detail=f"Database error: {e}")
